# Generated by Django 3.1.7 on 2023-08-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('recruiter', 'Recruiter Permission')]},
        ),
    ]
